import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

import NextTopLoader from 'nextjs-toploader';

import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'
import ContextProvider from '@/components/context';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ContextProvider>
          <NextTopLoader />
          <Header />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  )
}
